version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/LibreTube"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
